# Generated by Django 4.0.1 on 2022-02-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=6, unique=True)),
                ('url', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('redirect_count', models.IntegerField(default=0)),
                ('last_redirect', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-creation_date',),
            },
        ),
    ]
